name: Selenium CRUD Tests

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Run Create Leave Tests
      - name: Run CreateLeaveTest
        run: mvn test -Dtest=CreateLeaveTest

      # Run Update Leave Tests
      - name: Run UpdateLeaveTest
        run: mvn test -Dtest=UpdateLeaveTest

      # Run Delete Leave Tests
      - name: Run DeleteLeaveTest
        run: mvn test -Dtest=DeleteLeaveTest

      # Run Complete CRUD Tests
      - name: Run LeaveCRUDTest
        run: mvn test -Dtest=LeaveCRUDTest
